# The configuration format is quite straight forward. It is organised in sections and key/value pairs.
# The order of the sections or key/values pairs inside the sections does not matter nor does casing.
# Boolean values can be set using true, false, 1 or 0
# Floating point values must use . (point) as decimal separator











[General]
Type=Hotspot				# "Repeater" or "Hotspot". Defaults to "Repeater"
Callsign=EAXXXX
Address=0.0.0.0				# this is the computer interface for the outgoing connection. Usually leave it blank and it will use whatever is avaiable.
IcomAddress=172.16.0.20
IcomPort=20000
HBAddress=127.0.0.1				# address to use for connecting to the homebrew repeaters (MMDVMHost, DStarRepeater), defaults to 127.0.0.1
HBPort=20010
Latitude=41.530704
Longitude=2.185437
Description1=
Description2=
URL=
Language=Espanol				# valid values: English_UK, Deutsch, Dansk, Francais, Francais_2, Italiano, Polski, English_US, Espanol, Svenska, Nederlands_NL, Nederlands_BE, Norsk, Portugues
#up to 4 ircddb networks can be specified











[IRCDDB 1]
Enabled=1
Hostname=ircv4.openquad.net
Username=EAXXXX				# The ircDDB username defaults to the value defined for gateway callsign.
Password=











[IRCDDB 2]
Enabled=0
Hostname=
Username=				# The ircDDB username defaults to the value defined for gateway callsign.
Password=











[IRCDDB 3]
Enabled=0
Hostname=
Username=CHNGME				# The ircDDB username defaults to the value defined for gateway callsign.
Password=











[IRCDDB 4]
Enabled=0
Hostname=
Username=CHNGME				# The ircDDB username defaults to the value defined for gateway callsign.
Password=
# up to 4 repeaters can be added











[Repeater1]
Enabled=1
Band=B				# Each module has to have a band letter
Callsign=EAXXXX
Address=				# address where the repeater can be found, if left empty defaults to 127.0.0.1
Port=20011
Type=HB				# valid values: "HB" or "Icom"
Reflector=XRF266 B
ReflectorAtStartup=true				# if reflector is set, this defaults to true
ReflectorReconnect=30				# valid values: "Never", "Fixed", "5", "10", "15", "20", "25", "30", "60", "90", "120", "180"
Frequency=434.0
Offset=-0.0
RangeKm=20
Latitude=0.0
Longitude=0.0
AGL=
Description1=
Description2=
URL=
Band1=
Band2=
Band3=











[Repeater 2]
Enabled=0
Band=C				# Each module has to have a band letter
Callsign=				# Has to be less than 8 characters, if empty gateway call will be used
Address=				# address where the repeater can be found, if left empty defaults to 127.0.0.1
Port=20012
Type=HB				# valid values: "HB" or "Icom"
Reflector=
ReflectorAtStartup=true				# if reflector is set, this defaults to true
ReflectorReconnect=30				# valid values: "Never", "Fixed", "5", "10", "15", "20", "25", "30", "60", "90", "120", "180"
Frequency=434.0
Offset=-1.6
RangeKm=20
Latitude=0.0
Longitude=0.0
AGL=
Description1=
Description2=
URL=
Band1=
Band2=
Band3=











[Repeater 3]
Enabled=0
Band=D				# Each module has to have a band letter
Callsign=				# Has to be less than 8 characters, if empty gateway call will be used
Address=				# address where the repeater can be found, if left empty defaults to 127.0.0.1
Port=20013
Type=HB				# valid values: "HB" or "Icom"
Reflector=
ReflectorAtStartup=				# if reflector is set, this defaults to true
ReflectorReconnect=30				# valid values: "Never", "Fixed", "5", "10", "15", "20", "25", "30", "60", "90", "120", "180"
Frequency=434.0
Offset=-1.6
RangeKm=20
Latitude=0.0
Longitude=0.0
AGL=
Description1=
Description2=
URL=
Band1=
Band2=
Band3=











[Repeater 4]
Enabled=0
Band=A				# Each module has to have a band letter
Callsign=				# Has to be less than 8 characters, if empty gateway call will be used
Address=				# address where the repeater can be found, if left empty defaults to 127.0.0.1
Port=20014
Type=HB				# valid values: "HB" or "Icom"
Reflector=
ReflectorAtStartup=				# if reflector is set, this defaults to true
ReflectorReconnect=30				# valid values: "Never", "Fixed", "5", "10", "15", "20", "25", "30", "60", "90", "120", "180"
Frequency=434.0
Offset=-1.6
RangeKm=20
Latitude=0.0
Longitude=0.0
AGL=
Description1=
Description2=
URL=
Band1=
Band2=
Band3=











[APRS]
Enabled=0
PositionSource=				# Sets how the position is determined "Fixed" or "GPSD". this is ignored if DStargateway was built without GPSD support











[GPSD]
Address=				# GPSD address, defaults to 127.0.0.1
Port=				# GPSD port, defaults to 2947











[Log]
MQTTLevel=1				# defaults to 2, valid values are 0-6 with 0=None, 1=Debug, 2=Message, 3=Info, 4=Warning, 5=Error, 6=Fatal
DisplayLevel=1				# defaults to 2, valid values are 0-6 with 0=None, 1=Debug, 2=Message, 3=Info, 4=Warning, 5=Error, 6=Fatal
LogIRCDDBTraffic=				# Set to true to output ircddb traffic to the log, defaults to false











[MQTT]
Address=127.0.0.1
Port=1883
Keepalive=60
Authenticate=false
Username=mmdvm
Password=mmdvm
Name=dstar-gateway











[Paths]
Data=/usr/local/share/dstargateway.d/				# Path where the data (audio files etc) can be found











[Hosts Files]
HostsFiles=/usr/local/share/dstargateway.d				# Path where the downloaded host files are stored, make sure user dstar has write access
ReloadTimer=72				# Reload host files every X hours, must be greater than 24 hours. Defaults to 72 hours
CustomHostsfiles=/usr/local/share/dstargateway.d/hostfiles.d				# Place your custom host files in this directory, this dir must be different from datadir.
                                                              # Any hosts found here will override same host in downloaded files
                                                











[Dextra]
Enabled=1				# There is no reason to disable this
MaxDongles=5











[D-Plus]
Enabled=1				# There is no reason to disable this
MaxDongles=5
Login=				# defaults to the gateway callsign











[DCS]
Enabled=1				# There is no reason to disable this











[XLX]
Enabled=1











[D-Rats]
Enabled=0				# Defaults to false. The program need to be compiled with DRats support for DRats to be actually enabled











[Remote Commands]
Enabled=0
# Should only be used with respect to your local regulation! Many countries prohibit setting up private repeaters !











[Access Control]
WhiteList=				# Only affects network
BlackList=				# Only affects network
RestrictList=				# Only affects RF, call signs present in this list are now allowed to change reflector or unlink the repeater
# The Provided install routines install the program as a systemd unit. SystemD does not recommand "old-school" forking daemons nor does systemd
# require a pid file. Moreover systemd handles the user under which the program is started. This is provided as convenience for people who might
# run the program using sysv or any other old school init system.











[Daemon]
Daemon=0
PidFile=/var/run/dstargateway/dstargateway.pid				# pid file is in our case useless when running as a daemon  using systemd as systemd takes care of the service not being started twice
User=dstar				# user account the daemon will run under, ideally a user with low privileges. Switching to this user will only happen when the program is started as root











[Gateway]
Callsign=EA3EIZ
Username=
