[ModuleEchoLink]
NAME=EchoLink
ID=2
TIMEOUT=0
#ALLOW_IP=192.168.1.0/24
#DROP_INCOMING=^()$
#REJECT_INCOMING=^()$
#ACCEPT_INCOMING=^(.*)$
#REJECT_OUTGOING=^()$
#ACCEPT_OUTGOING=^(.*)$
#REJECT_CONF=0
#CHECK_NR_CONNECTS=2,300,120
SERVERS=servers.echolink.org
CALLSIGN=EAXXXX-L
PASSWORD=PASSWORD
SYSOPNAME=430.925 T77
LOCATION=In Conference *REM-ESP*
PROXY_SERVER=elp034.pi9noz.hamnet.nl
PROXY_PORT=8100
PROXY_PASSWORD=PUBLIC
MAX_QSOS=1
MAX_CONNECTIONS=1
#LINK_IDLE_TIMEOUT=300
AUTOCON_ECHOLINK_ID=3386
#USE_GSM_ONLY=1
#DEFAULT_LANG=en_US
DESCRIPTION="Este nodo no permite conexiones\n"
